labelPRBasedOnFilePath:
    Bot:
      - ./packages/bot-*/**/*
    Components:
      - ./packages/components/**/*
    Core:
      - ./packages/core/**/*
    P2P:
      - ./packages/p2p/**/*
    Repo:
      - ./*
    Shared:
      - ./packages/shared/**/*
    Trader:
      - ./packages/trader/**/*
    Translations:
      - ./packages/translations/**/*
    Docs:
      - ./*.md
      - ./**/*.md
  verifyTitles:
    titleRegexp: ^([a-z]{2,}(\|[a-z]{2,})?)\/([a-z0-9]{3,}((_[a-z0-9]+)+)?)(\s\[\w+\])?$
