image: node:11.15.0

cache:
  untracked: true
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/
    - packages/*/node_modules

stages:
  - setup
  - test

setup:
  stage: setup
  script: npm run bootstrap

test_all:
  stage: test
  script: npm run test
