language: node_js
cache:
    directories: 
        - node_modules
matrix:
    fast_finish: true
node_js:
    - node
notifications:
    email: false
before_install: 
    - if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi
    - npm install
install: npm run test:full
