version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/ssl:ro
