name: Download Artifacts
description: 'Download artifacts'
runs: 
  using: composite
  steps:
  - name: Download artifact
    id: download-artifact
    uses: dawidd6/action-download-artifact@v2
    with:
      workflow_conclusion: success
      run_id: ${{ github.event.workflow_run.id }}
      name: 'artifacts-${{ github.event.workflow_run.id }}'
    shell: bash