version: 2.1
orbs:
  k8s: circleci/kubernetes@0.7.0
commands:
  git_checkout_from_cache:
    description: "Git checkout and save cache"
    steps:
      - restore_cache:
          name: Git restore cache
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - run:
          name: Fetch git tags
          command: |
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
            # Fetch tags if git cache is present
            if [ -e /home/circleci/project/.git ]
            then
              git fetch origin --tags
            fi
      - checkout
      - run:
          name: Compress git objects
          command: git gc
      - save_cache:
          name: Git save cache
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
  npm_install_from_cache:
    description: "npm install and save cache"
    steps:
      - restore_cache:
          keys:
            - node-
      - run:
          name: Install npm packages
          command: npm run bootstrap
      - run:
          name: "create cache key"
          command: echo $(find ./packages/ -name package-lock.json -type f -exec md5sum {} \; | md5sum | cut -d' ' -f1) >> CACHE_KEY1
      - save_cache:
          key: node-{{ checksum "CACHE_KEY1" }}
          paths:
            - "node_modules"
            - "packages/*/node_modules"
  build:
    description: "Build"
    steps:
      - run:
          name: "build packages"
          command: npm run build:local
      - run:
          name: "build core"
          command: node_modules/lerna/cli.js exec --scope @deriv/core -- npm run build

  deploy_gh_pages:
    description: "Deploy to static branches"
    parameters:
      target_branch:
        type: string
    steps:
      - attach_workspace:
          at: packages/core/dist
      - run:
          name: Tag build
          command: echo "<< parameters.target_branch >>-$(date -u +'%Y-%m-%dT%H:%M:%SZ')" > packages/core/dist/version
      - run:
          name: Install and configure dependencies
          command: |
            mkdir "${HOME}/.npm-packages"
            npm config set prefix "${HOME}/.npm-packages"
            npm i -g gh-pages
            git config user.email "ci-build@binary.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "51:d4:cc:51:58:08:a1:53:13:77:fa:40:41:a0:94:d2"
      - run:
          name: Deploy docs to gh-pages branch
          command: /home/circleci/.npm-packages/bin/gh-pages -d packages/core/dist --branch << parameters.target_branch >> --message '[skip ci]'

  docker_build_push:
    description: "Build and Push image to docker hub"
    parameters:
      docker_image_latest_tag:
        type: string
        default: "latest-staging"
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Building docker image
          command: |
            TAG=${CIRCLE_TAG:-$CIRCLE_SHA1}
            docker build -t ${DOCKHUB_ORGANISATION}/deriv-app:${TAG} -t ${DOCKHUB_ORGANISATION}/deriv-app:<< parameters.docker_image_latest_tag >> .
      - run:
          name: Pushing Image to docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${DOCKHUB_ORGANISATION}/deriv-app
  k8s_deploy:
    description: "Deploy to k8s cluster"
    parameters:
      k8s_svc_name:
        type: string
        default: "staging-deriv-app"
    steps:
      - k8s/install-kubectl
      - run:
          name: Deploying to k8s cluster for service deriv-app
          command: |
            TAG=${CIRCLE_TAG:-$CIRCLE_SHA1}
            for SERVER_ID in {1..5}
            do
              KUBE_SERVER_REF="KUBE_SERVER_$SERVER_ID"
              SERVICEACCOUNT_TOKEN_REF="SERVICEACCOUNT_TOKEN_$SERVER_ID"
              CA_CRT_REF="CA_CRT_$SERVER_ID"
              if [ ! -z "${!KUBE_SERVER_REF}" ]
              then
                echo "Deploying to cluster $SERVER_ID"
                CA_CRT="${!CA_CRT_REF}"
                KUBE_SERVER="${!KUBE_SERVER_REF}"
                SERVICEACCOUNT_TOKEN="${!SERVICEACCOUNT_TOKEN_REF}"
                echo $CA_CRT | base64 --decode > ca.crt
                kubectl --server=${KUBE_SERVER} --certificate-authority=ca.crt --token=$SERVICEACCOUNT_TOKEN set image deployment/<< parameters.k8s_svc_name >> << parameters.k8s_svc_name >>=${DOCKHUB_ORGANISATION}/deriv-app:${TAG}
              fi
            done
jobs:
  build_deploy_staging:
    docker:
      - image: circleci/node:12.18.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - build
      - deploy_gh_pages:
          target_branch: staging
      - docker_build_push
      - k8s_deploy
    environment:
      NODE_ENV: staging
  build_deploy_production:
    docker:
      - image: circleci/node:12.18.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - build
      - deploy_gh_pages:
          target_branch: production
      - docker_build_push:
          docker_image_latest_tag: latest
      - k8s_deploy:
          k8s_svc_name: production-deriv-app
    environment:
      NODE_ENV: staging

workflows:
  build_deploy_staging:
    jobs:
      - build_deploy_staging:
          context: binary-frontend-artifact-upload
          filters:
            branches:
              only: /^master$/
  build_deploy_production:
    jobs:
      - build_deploy_production:
          context: binary-frontend-artifact-upload
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
