name: send_slack_notifications
description: Send Slack notifications
runs:
  using: composite
  steps:
  - name: Send Slack Notification on Success
   
    env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        status: ${{ inputs.status }}
        release_type: ${{ inputs.release_type }}
        version: ${{ inputs.version }}

    if: status == 'success'
    run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{
        "text": "'"${{ release_type }}"' Release succeeded for app.deriv.com with version *'"${{ version }}"'*"
        }' \
        $SLACK_WEBHOOK
    shell: bash
  
  - name: Send Slack Notification on Failure
    if: status == 'failure'
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      status: ${{ inputs.status }}
      release_type: ${{ inputs.release_type }}
      version: ${{ inputs.version }}
    run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "'"${{ release_type }}"' Release failed for app.deriv.com with version *'"${{ version }}"'*"
          }' \
          $SLACK_WEBHOOK
    shell: bash