name: send_slack_notifications
description: Send Slack notifications
inputs:
  SLACK_WEBHOOK_URL:
    description: 'Slack webhook URL'
    required: true
  status:
    description: 'Job status'
    required: true
  release_type:
    description: 'Release type'
    required: true
  version:
    description: 'Version'
    required: true
    default: 'N/A'
runs:
  using: composite
  steps:
  - name: check env vars
    run: |
      echo "SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}"
      echo "status: ${{ inputs.status }}"
      echo "release_type: ${{ inputs.release_type }}"
      echo "version: ${{ inputs.version }}"
    shell: bash
  - name: Send Slack Notification on Success
    if: ${{ inputs.status }} == 'success'
    run: |-
        curl -X POST -H 'Content-type: application/json' \
        --data '{
        "text": "'"${{ inputs.release_type }}"' Release succeeded for app.deriv.com with version *'"${{ inputs.version }}"'*"
        }' \
          ${{ inputs.SLACK_WEBHOOK_URL }}
    shell: bash
  
  - name: Send Slack Notification on Failure
    if: ${{ inputs.status }} == 'failure'

    run: |-
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "'"${{ inputs.release_type }}"' Release failed for app.deriv.com with version *'"${{ inputs.version }}"'*"
          }' \
          ${{ inputs.SLACK_WEBHOOK_URL }}
    shell: bash