name: Clover
on: [ push ]
env:
  CI: true

jobs:
  test:
    name: Clover
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@master
        with:
          node-version: '14.17.1'

      - name: Install npm dependencies
        run: npm install # switch to `npm ci` when Node.js 6 support is dropped

      - name: Bootstrap Project
        run: npm run bootstrap && npm run build # switch to `npm ci` when Node.js 6 support is dropped

      - name: Run tests
        run: npm run test:jest

      - name: Clover
        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clover-file: ./coverage/clover.xml
