on: 
  push:
    branches:
      - master
      
  workflow_run:
    workflows: ['Deriv App PR Test Workflow']
    types:
        - completed 
name: Coveralls
jobs:
  build:
    name: Reporter
    runs-on: Runner_8cores_Deriv
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: './.github/actions/setup_node'
      - name: Install dependencies
        uses: "./.github/actions/npm_install_from_cache"
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          name: 'artifacts-${{ github.event.workflow_run.id }}'
      - name: Test
        run: JEST_MAX_WORKERS=95% npm run test:jest -- --collectCoverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
