name: Run Eslint and Stylelint
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install, bootstrap
        run: |
          npm install
          npm run bootstrap
          npm run build
      - name: Run ESLint
        run: npm run test:eslint
      - name: Run stylelint
        run: npm run test:stylelint
