name: Deriv App Integration Test Workflow

on:
    workflow_run:
        workflows: ['Deriv App PR Test Workflow']
        types:
            - completed
jobs:
  integration_tests:
    name: Run Integration Tests
    runs-on: Runner_8cores_Deriv-app
    environment: Preview
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: "./.github/actions/setup_node"
    - name: Install dependencies
      uses: "./.github/actions/npm_install_from_cache"
    - name: Download Artifacts
      uses: "./.github/actions/download_artifacts"
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Run integration tests
      run: npm run test:e2e
