name: StyleLint, ESlint and Coverage Workflow
on: [ "pull_request" ]
jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install, bootstrap and make test coverage
        run: |
          npm install
          npm run bootstrap
          npm run build
      - name: Run Tests
        run: npm run test:jest
      - name: Run ESLint
        run: npm run test:eslint
      - name: Run Stylelint
        run: npm run test:stylelint
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          name: codecov-umbrella
          verbose: true
