name: Node.js CI

on: push

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 14.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run bootstrap && npm run build
      - name: TestCoverage
        id: testCoverage
        uses: raulanatol/jest-coverage-comment-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jest-command: 'npm run test:ci'
